# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Saikorian',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lastUpdated', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('rollNumber', models.IntegerField(default='', max_length=5)),
                ('donation', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(blank=True)),
                ('emailId', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ('rollNumber',),
            },
        ),
    ]
