# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saikor_webservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saikorian',
            name='rollNumber',
            field=models.IntegerField(default=''),
        ),
    ]
