# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saikor_webservice', '0002_auto_20161210_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saikorian',
            name='donation',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
